---
title: "Lobser exploration"
format: html
editor_options: 
  chunk_output_type: console
---
```{r}
# load packages ----
library(tidyverse)
library(dplyr)
library(janitor)
```

```{r}
# read in data ----
lobsters <- read_csv(here("data", "Lobster_Abundance_All_Years_20210412.csv"), na = c("-99999", "")) |>
  clean_names() |>
  uncount(count)   # dplyr::uncount() : count told us the total number of lobsters of this size in the lobster transect. there are other ways to know this info, so uncount() took out this column 
```

```{r}
# total counts and mean carapace lengths of lobsers by site and year

lobsters_counts_means <- lobsters |>
  group_by(site, year) |>
  summarise(total_count = n(),
            mean_carapace = mean(size_mm, rm.na = TRUE))

# plot it
ggplot(data = lobsters_counts_means, aes(x = year, y = total_count, color = site, facet_wrap(site))) +
  geom_point() +
  geom_line() +
  labs(x = "Year", y = "Total number of lobsters")
```

```{r}
# Legal lobsters 2020
lobsters_2020 <- lobsters |>
  filter(year == 2020)

# find counts of lobsters observes at each site that are above and below the legal limit
lobsters_2020_legal <- lobsters_2020 |>
  mutate(legal = case_when(
    size_mm >= 79.76 ~ "yes",
    size_mm < 79.76 ~ "no"), rm.na = TRUE) |>
  group_by(site, legal) |>
  summarise(total_count = n())

# make a stacked column graph that shows the proportion of legal and non-legal lobsters at each site
ggplot(data = lobsters_2020_legal, aes(x = site, y = total_count)) +
  geom_col(position = "fill", aes(fill = legal))

# the Isla Vista Reef and the Napels Reef have the highest proportions of legal lobsters in 2020. This could be because they are the only two sites within a Marine Protected Area.

```


```{r}
# filter() practice ----
ex_a <- lobsters |>
  filter(site %in% c("IVEE", "CARP", "NAPL"))
unique(ex_a$site)

ex_b <- lobsters |>
  filter(month == 8)
unique(ex_b$month)

ex_c <- lobsters |>
  filter(site == "AQUE" | size_mm > 70)

ex_d <- lobsters |>
  filter(site != "NAPL")
unique(ex_d$site)
```

```{r}
# group_by() |> summarize() practice ----
ex_e <- lobsters |>
  group_by(site) |>
  summarize(mean_length = mean(size_mm, rm.na = TRUE),
            std_dev_length = sd(size_mm))

ex_f <- lobsters |>
  group_by(site, month) |>
  summarize(max_carapace_length = max(size_mm, rm.na = TRUE))
```

```{r}
# mutate() practice ----
ex_g <- lobsters |>
  mutate(length_cm = size_mm / 10)

ex_h <- lobsters |>
  mutate(site = tolower(site))

ex_i <- lobsters |>
  mutate(area = as.character(area))
class(lobsters$area)
```

```{r}
# case_when() practice ----
ex_j <- lobsters |>
  mutate(size_bin = case_when(
    size_mm <= 70 ~ "small",
    size_mm > 70 ~ "large"
  ))

ex_k <- lobsters |>
  mutate(designation = case_when(
    site %in% c("IVEE", "NAPL") ~ "MPA",
    !site %in% c("IVEE", "NAPL") ~ "not MPA"
  ))
```









